### ISSUE TITLE
Support verbose diagnostics via CachedSchemaRegistryClient.testCompatibilityVerbose

### ISSUE THREAD

**Issue by hertzsprung** [domnikl/schema-registry-gitops#100]
It would be helpful if schema incompatibility error messages could be displayed (either via the `--verbose` CLI option or some other mechnism).   This is supported by [`CachedSchemaRegistryClient.testCompatibilityVerbose()`](https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java#L635).

**Comment by domnikl** [comment]
@hertzsprung I think it's a very good idea! Didn't have yet time to implement it, but will in the coming days get to it.

**Comment by domnikl** [comment]
@hertzsprung is now implemented in the latest release 1.8.0, thanks for suggesting it 👍🏻
