### ISSUE TITLE
Support for clustered setup

### ISSUE THREAD

**Issue by martinberanek** [domnikl/schema-registry-gitops#17]
If using schema registry in the cluster (for HA), only one of the nodes is leading and can write to internal schema registry topic. That's why `CachedSchemaRegistryClient` accepts both the single string as baseUrl (which is then split by comma) or list directly.

Please can you support defining this list in `schema.registry.url` property?

I guess that change is needed only in [Factory.kt](https://github.com/domnikl/schema-registry-gitops/blob/main/src/main/kotlin/dev/domnikl/schema_registry_gitops/Factory.kt#L27) and can be done backward compatible.

**Comment by domnikl** [comment]
It's included in the latest release 1.1.0, thanks for your input!
