### ISSUE TITLE
Possible to use tool for validating multiple schema for given subject?

### ISSUE THREAD

**Issue by patrickjmccauley** [domnikl/schema-registry-gitops#23]
Is it possible to validate a schema file containing an array of valid schema against the current state of the registry? It appears that the only communication with the confluent schema registry client occurs in `SchemaRegistryClient.getLatestSchema`, meaning that the diff considers a single version of the requested schema against an array.

**Comment by domnikl** [comment]
Hi @patrickjmccauley,
currently it is not possible. Could you please tell me more about the use case you have to do this?
