### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by jamielwhite** [domnikl/schema-registry-gitops#239]
Hi there, my team is using is using your image to manage our schemas, and we've had several vulnerabilities get flagged for the current version (1.9.0). I saw there was a [recent PR](https://github.com/domnikl/schema-registry-gitops/pull/215) to address most if not all of those. Are there any plans to release this to a new image version?

Thanks for your work on this tool!

**Comment by domnikl** [comment]
Hi @jamielwhite! Glad you find the tool useful ❤️  I plan on releasing later today, didn't have the time yet and want to incorporate remaining renovate updates as well.

**Comment by domnikl** [comment]
Just released a new version: 1.10.0: https://github.com/domnikl/schema-registry-gitops/releases/tag/1.10.0
