### ISSUE TITLE
Schema is not updated when "doc" attribute changed

### ISSUE THREAD

**Issue by martinberanek** [domnikl/schema-registry-gitops#26]
I have changed some "doc" attributes in my avro schema, but the tool doesn't update them in schema registry.

- It correctly checks that the schema is compatible.
- Then it downloads latest version from registry.
- But the comparsion of these two schemas returns true so the schema is not updated then.
  https://github.com/domnikl/schema-registry-gitops/blob/186efb2e038c5141128c736795dfed61b22e512e/src/main/kotlin/dev/domnikl/schema_registry_gitops/state/Diffing.kt#L69

At first it looks like no problem, but when applications are trying get schemaid from registry (`POST /subjects/{subject}`), the registry returns `403 Schema not found `(even with `normalize=true` parameter)

In [documentation](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#schema-normalization), they wrote that

> Schema Registry will use the string representation of the schema for registration/lookup

I think that tool should use same method for schema comparison as registry do.

**Comment by martinberanek** [comment]
I prepared "quickfix" for my case and replace the deepEquals comparison with

`remoteSchema.canonicalString().equals(subject.schema.canonicalString())`

looks good for our usecase

**Comment by domnikl** [comment]
Adjusted it in [53b648e](https://github.com/domnikl/schema-registry-gitops/commit/53b648e8c6cca4bfc837414db16d9eec699a3cf0), will release a new version with it later.
