### ISSUE TITLE
Allow usage of multiple input files

### ISSUE THREAD

**Issue by S1M0NM** [domnikl/schema-registry-gitops#30]
We use schema-registry-gitops in our build pipeline to manage the schema registry.
The tool currently only supports the use of one input file, which becomes confusing and long with a larger number of subjects/schemas.

Would it be possible to extend the functionality so that multiple input files could be used? For example, to allow separation by domains

**Comment by domnikl** [comment]
First of all: thanks for using schema-registry-gitops! Would totally make sense to load different files and I think I would be possible as well. Give me some time to try out what the best way to implement is and I'll get back to you.

**Comment by domnikl** [comment]
@S1M0NM I merged support for multiple input files and released 1.7.0 🎉

**Comment by S1M0NM** [comment]
@domnikl Thank you for the quick implementation! Tested it and it works as expected.
